services:
  postgres:
    image: postgres:15-alpine
    container_name: fitness_club_db
    environment:
      POSTGRES_DB: ${DB_NAME:-fitness_club_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fitness_network
    env_file:
      - .env

  app:
    build: .
    container_name: fitness_club_app
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME:-fitness_club_db}?currentSchema=${DB_NAME:-fitness_club_db}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
      REMEMBER_ME_KEY: ${REMEMBER_ME_KEY}
      STATS_SERVICE_URL: http://stats-service:8081
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fitness_network
    volumes:
      - ./logs:/app/logs
      - ~/.m2:/root/.m2  # ЭТА СТРОКА СОХРАНИТ ЗАВИСИМОСТИ
    env_file:
      - .env

  stats-service:
    build: ./stats-service
    container_name: fitness_club_stats
    ports:
      - "8081:8081"
    environment:
      DB_CONNECTION: postgres://${DB_USERNAME:-postgres}:${DB_PASSWORD}@postgres:5432/${DB_NAME:-fitness_club_db}?sslmode=disable
      PORT: 8081
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fitness_network
    env_file:
      - .env

networks:
  fitness_network:
    driver: bridge

volumes:
  postgres_data: